---
- name: Ensure role dependencies are installed
  ansible.builtin.apt:
    name: "{{ __tuned__role_dependencies }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Ensure tuned service is enabled and started
  ansible.builtin.systemd:
    name: tuned.service
    state: started
    enabled: true
    daemon_reload: true

- name: Get the active tuned profile
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      tuned-adm active | awk '{print $NF}'
  register: tuned__active_profile
  changed_when: false

- name: Get the recommended tuned profile
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      tuned-adm recommend
  register: tuned__recommended_profile
  changed_when: false

- name: Configure tuned to use the parameterized profile
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      tuned-adm profile {{ tuned__profile }}
      tuned-adm active | awk '{print $NF}'
  when: tuned__profile is defined and tuned__profile != tuned__active_profile.stdout
  register: tuned__configured_profile
  changed_when: tuned__configured_profile.stdout != tuned__active_profile.stdout

- name: Configure tuned to use the recommended profile
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      tuned-adm profile {{ tuned__recommended_profile.stdout }}
      tuned-adm active | awk '{print $NF}'
  when: tuned__profile is undefined and tuned__recommended_profile.stdout != tuned__active_profile.stdout
  register: tuned__configured_profile
  changed_when: tuned__configured_profile.stdout != tuned__active_profile.stdout
